---
galaxy_info:
  author: Viacheslav Kuzmenko
  description: install common and extra packages
  company: ZEO Alliance
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - packaging
dependencies: []
