---
- name: provision
  hosts: ec2
  gather_facts: yes
  become: yes

  vars_files:
    - vars/user
    - vars/production
  roles:
#    - common-prod
#    - common
#    - sudo
#    - auth-reset
#    - mysql
#    - nginx-base
     - postfix
