---
- name: set mailname
  copy: >
    content='{{ inventory_hostname }}{{ '\n' }}'
    dest=/etc/mailname
  tags:
    - mailname

- name: configure main.cf
  template: >
    src=main.cf.j2
    dest=/etc/postfix/main.cf
  notify:
    - restart postfix

- name: configure master.cf
  template: >
    src=master.cf.j2
    dest=/etc/postfix/master.cf
  notify:
    - restart postfix
