---
- include: install.yml
  tags:
    - install_postfix
    - install

- include: configure.yml
  tags:
    - configure_postfix
    - configure

- include: sasl.yml
  when: postfix_smtp_sasl_password_maps is defined
  tags:
    - sasl_postfix
    - sasl

- include: aliases.yml
  tags:
    - aliases_postfix
    - aliases

- include: header.yml
  tags:
    - header_postfix
    - header
