---
- name: install mysql server
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=600
  with_items:
    - mysql-server
    - python-mysqldb
  environment:
    DEBIAN_FRONTEND: noninteractive
