---
- name: create directory
  file: >
    path=/etc/update-motd.d
    state=directory

- name: copy config files
  template: >
    src={{ item }}.j2
    dest=/etc/update-motd.d/{{ item }}
    mode=0755
  with_items:
    - 00-header

- name: remove motd file
  file: >
    path=/etc/motd
    state=absent

- name: create symlink
  file: >
    src=/var/run/motd
    dest=/etc/motd
    state=link
    force=yes
