---
- name: install openssh-server and openssh-client
  apt: >
    name={{ item }}
    update_cache=yes
    cache_valid_time=86400
    state=latest
  with_items:
    - openssh-client
    - openssh-server
  notify:
    - reload ssh
