---
galaxy_info:
  author: Viacheslav Kuzmenko
  description: preprovision instance
  company: ZEO Alliance
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - system
dependencies:
  - { role: cloudmccloud-list, when: ansible_distribution_major_version == '6' }
