---
- name: set localtime
  file: >
    src=/usr/share/zoneinfo/{{ timezone }}
    dest=/etc/localtime

- name: set timezone
  copy: >
    content='{{ timezone }}{{ '\n' }}'
    dest=/etc/timezone

- name: update timezone
  command: >
    dpkg-reconfigure --frontend noninteractive tzdata
